[aws]
profile = "saml"
secret_name = "realtime-transcribe-service/dev/app-config"

[app]
REDIS_URL = "rediss://clustercfg.dev-redis.xxxxxx.ap-east-1.cache.amazonaws.com:6379/0"
REDIS_SEQUENCE_STATE_KEY_PREFIX = "ods-dev:realtime-transcribe-service:expect-transcript-seq-num"
REDIS_OWNERSHIP_GUARD_KEY_PREFIX = "ods-dev:realtime-transcribe-service:conversation-owner"
KAFKA_BOOTSTRAP_SERVERS = "b-1.dev-msk.xxxxxx.c2.kafka.ap-east-1.amazonaws.com:9098,b-2.dev-msk.xxxxxx.c2.kafka.ap-east-1.amazonaws.com:9098"
