[aws]
profile = "saml"
secret_name = "realtime-transcribe-service/preprod/app-config"

[app]
REDIS_SEQUENCE_STATE_KEY_PREFIX = "preprod:realtime-transcribe-service:expect-transcript-seq-num"
REDIS_OWNERSHIP_GUARD_KEY_PREFIX = "preprod:realtime-transcribe-service:conversation-owner"
